[package]
name = "Image-Inverter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "image_inverter"
path = "src/main.rs"
subsystem = "windows"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"